export const gift_set= [{ "id" : "an1",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw5e7830a6/crop/025144398_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Limited Edition",
    "category1": "Spring Gift Bundle", 
    "Amount": "112.00",
    "Rating": "3",
    "desc":"Why you'll love it: this one-of-a-kind gift for mom (or you) comes wrapped and ready to give. What's inside: 8 new favorites, including 4 exclusives you can't get anywhere else.",

  }, { "id" : "an2",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw622857e3/crop/025144301_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Champagne Toast",
    "category1": "Gift Box Set",
    "Amount": "34.95",
    "Rating": "5",
    "desc":"What it smells like: a fruity, sweet, sparkling spritzer. Fragrance notes: bubbly champagne, sparkling berries and juicy tangerine.",
  }, { "id" : "an3",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dwe183ea7e/crop/025144307_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "A Thousand Wishes" ,
    "category1": "Gift Box Set",
    "Amount": "34.95",
    "Rating": "4.5",
    "desc":"What it smells like: a fruity, sweet, sparkling spritzer. Fragrance notes: bubbly champagne, sparkling berries and juicy tangerine."
  }, { "id" : "an4",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dwcbace8ea/crop/025144315_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Strawberry Pound Cake",
    "category1": "Mini Gift Box Set",
    "Amount": "17.50",
    "Rating": "4",
    "desc":"What it smells like: a sweet, heart-warming celebration. Fragrance notes: pink prosecco, sparkling quince, crystal peonies, gilded amber and amaretto crème"
  }, { "id" : "an5",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw704faaf7/crop/025144303_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Japanese Cherry Blossom",
    "category1": "Gift Box Set",
    "Amount": "34.95",
    "Rating": "5",
    "desc":"What it smells like: the sweet, airy treat you love. What it does: makes gifting so easy and puts a smile on their face.",
  }, { "id" : "an6",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw0797f770/crop/025144313_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Gingham Love",
    "category1": "Mini Gift Box Set",
    "Amount": "17.50",
    "Rating": "2.5",
    "desc":"What it smells like: the sweet, airy treat you love. What it does: makes gifting so easy and puts a smile on their face.",
  }, { "id" : "an7",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw7aaefd47/crop/025144297_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Pure Wonder",
    "category1": "Gift Box Set",
    "Amount": "34.95",
    "Rating": "5",
    "desc":"What it smells like: the fragrance equivalent of your little black dress—beautiful, timeless and undeniably feminine. Fragrance notes: Japanese cherry blossom, Asian pear, fresh mimosa petals, white jasmine and blushing sandalwood.",
  }, { "id" : "an8",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw816a87d5/crop/025144299_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Sunshine Mimosa",
    "category1": "Gift Box Set",
    "Amount": "34.95",
    "Rating": "2.5",
    "desc":"What it smells like: the fragrance equivalent of your little black dress—beautiful, timeless and undeniably feminine. Fragrance notes: Japanese cherry blossom, Asian pear, fresh mimosa petals, white jasmine and blushing sandalwood.",

  },{ "id" : "an9",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw850c06fd/crop/025144309_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Gingham",
    "category1": "Gift Box Set",
    "Amount": "34.95",
    "Rating": "3",
    "desc":"What it smells like: the sweet, airy treat you love. What it does: makes gifting so easy and puts a smile on their face.",

  },{ "id" : "an10",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw9707153a/crop/025144295_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Clean Slate",
    "category1": "Gift Box Set",
    "Amount": "34.95",
    "Rating": "4.5",
    "desc":"What it smells like: the fragrance equivalent of your little black dress—beautiful, timeless and undeniably feminine. Fragrance notes: Japanese cherry blossom, Asian pear, fresh mimosa petals, white jasmine and blushing sandalwood.",

  },{ "id" : "an11",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw2eb9753a/crop/025144497_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Japanese Cherry Blossom",
    "category1": "Mini Gift Set",
    "Amount": "14.05",
    "Rating": "5",
    "desc":"Why you'll love it: this one-of-a-kind gift for mom (or you) comes wrapped and ready to give. What's inside: 8 new favorites, including 4 exclusives you can't get anywhere else.",

  },{ "id" : "an12",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw12e96985/crop/025144311_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "A Thousand Wishes",
    "category1": "Mini Gift Box Set",
    "Amount": "17.50",
    "Rating": "5",
    "desc":"Why you'll love it: this one-of-a-kind gift for mom (or you) comes wrapped and ready to give. What's inside: 8 new favorites, including 4 exclusives you can't get anywhere else.",

  },{ "id" : "an13",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw2fc56f5c/crop/025146197_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Lavender Lovelies",
    "category1": "Gift Set",
    "Amount": "14.95",
    "Rating": "4",
    "desc":"What it smells like: the fragrance equivalent of your little black dress—beautiful, timeless and undeniably feminine. Fragrance notes: Japanese cherry blossom, Asian pear, fresh mimosa petals, white jasmine and blushing sandalwood.",

  },{ "id" : "an14",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw4a30d81a/crop/025144305_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New!",
    "name": "Eucalyptus Spearmint",
    "category1": "Gift Box Set",
    "Amount": "34.95",
    "Rating": "1",
    "desc":"What it smells like: the fragrance equivalent of your little black dress—beautiful, timeless and undeniably feminine. Fragrance notes: Japanese cherry blossom, Asian pear, fresh mimosa petals, white jasmine and blushing sandalwood.",
  },{ "id" : "an15",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw8c4423d3/crop/025143509_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New Fragrance",
    "name": "Gingham",
    "category1": "Mini Gift Set",
    "Amount": "14.95",
    "Rating": "5",
    "desc":"Why you'll love it: this one-of-a-kind gift for mom (or you) comes wrapped and ready to give. What's inside: 8 new favorites, including 4 exclusives you can't get anywhere else.",

  },{ "id" : "an16",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dwb8678ec9/crop/025143901_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "New Fragrance",
    "name": "Sweet Pea",
    "category1": "Mini Gift Set",
    "Amount": "14.95",
    "Rating": "5",
    "desc":"Why you'll love it: this one-of-a-kind gift for mom (or you) comes wrapped and ready to give. What's inside: 8 new favorites, including 4 exclusives you can't get anywhere else.",

  },{ "id" : "an17",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw22234b1a/crop/025145996_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "Online Exclusive",
    "name": "Pink Pineapple Sunrise",
    "category1": "Single Wick Candle",
    "Amount": "12.00",
    "Rating": "3",
    "desc":"What it smells like: the sweet, airy treat you love. What it does: makes gifting so easy and puts a smile on their face.",

  },{ "id" : "an18",
    "pImg": "https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.216/dw/image/v2/BBDL_PRD/on/demandware.static/-/Sites-master-catalog/default/dw7143cf70/crop/025143597_crop.jpg?sw=500&sh=600&sm=fit&q=75&yocs=o_s_",
    "category": "Online Exclusive",
    "name": "Fresh Coconut",
    "category1": "Fragrance Refill & Plug Bundle",
    "Amount": "18.00",
    "Rating": "5",
    "desc":"What it smells like: the sweet, airy treat you love. What it does: makes gifting so easy and puts a smile on their face.",
  
  }]