export const allProducts = [
  {
    id: "At1",
    pName: "f",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "5",
  },
  {
    id: "At2",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At3",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At4",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At5",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At6",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At7",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At8",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At9",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At10",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At11",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At12",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At13",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At14",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At15",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At16",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At17",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At18",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At19",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
  {
    id: "At20",
    pName: "null",
    pImg: "https://dummyimage.com/600x400/000/fff",
    pCat: "null",
    Amount: "null",
    Rating: "null",
  },
];
