export const TodaysTopOfferSlider = [
  {
    id: "ar1",
    offerName: "Limited time only! Online only!",
    pName: "Spring Gift Bundle",
    discount: "$40 with any $40 purchase",
    limit: "Limit 1",
    link: "/",
  },
  {
    id: "ar2",
    offerName: "Ends today!",
    pName: "All Full-Size Body Care (Including Aromatherapy!)",
    discount: "Buy 3, Get 3 FREE",
    limit: "Lowest-priced items are free",
    link: "/",
  },
  {
    id: "ar3",
    offerName: "",
    pName: "Wallflowers Fragrance Refills",
    discount: "5/$18 or 7/$24",
    limit: "",
    link: "/",
  },
  {
    id: "ar4",
    offerName: "",
    pName: "Mother's Day Gifts",
    discount: "Under $15",
    limit: "",
    link: "/",
  },
  {
    id: "ar5",
    offerName: "",
    pName: "Hand Soaps",
    discount: "6/$27 or 4/$20",
    limit: "",
    link: "/",
  },
  {
    id: "ar6",
    offerName: "",
    pName: "Single Wick Candles",
    discount: "2/$22",
    limit: "",
    link: "/",
  },
  {
    id: "ar7",
    offerName: "",
    pName: "Travel, Hand & Lip Care",
    discount: "Buy 2 Get 1 Free",
    limit: "Lowest-priced item is free",
    link: "/",
  },
];